#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
快速投研分析入口 (Quick Market Analysis Entry)
仅运行 Market Analyst (技术量价分析师) + 多空辩论与风控决策，并直接输出结构化 Markdown 文档。

使用方法:
    python quick_analyze.py 517520
    python quick_analyze.py 517520.etf 2026-08-14
    python quick_analyze.py 600519
    python quick_analyze.py   # 交互式输入代码
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# Ensure project root in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Load .env
load_dotenv(PROJECT_ROOT / ".env")

from tradingagents.default_config import DEFAULT_CONFIG
from tradingagents.graph.trading_graph import TradingAgentsGraph
from tradingagents.dataflows.a_stock import is_etf_ticker, _normalize_ticker, _market_today
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown

console = Console()


def format_markdown_report(ticker: str, clean_code: str, trade_date: str, final_state: dict, decision: str) -> str:
    """Format full multi-agent state into a clean, comprehensive Markdown report."""
    is_etf = is_etf_ticker(ticker)
    asset_type = "A股指数ETF (Index ETF)" if is_etf else "A股上市公司 (Stock)"
    
    market_report = final_state.get("market_report", "暂无市场分析报告").strip()
    investment_plan = final_state.get("investment_plan", str(decision)).strip()
    trader_plan = final_state.get("trader_investment_plan", "").strip()
    
    debate_state = final_state.get("investment_debate_state", {})
    bull_history = debate_state.get("bull_history", "")
    bear_history = debate_state.get("bear_history", "")
    judge_decision = debate_state.get("judge_decision", "")

    risk_state = final_state.get("risk_debate_state", {})
    risk_judge = risk_state.get("judge_decision", "")

    report_lines = [
        f"# 📈 投研分析报告：{clean_code} ({ticker})",
        "",
        "> **免责声明**：本报告由 TradingAgents 多 Agent 投研系统自动生成，仅供研究参考，不构成任何投资建议。",
        "",
        "## 📌 基本信息",
        f"- **标的代码**：`{ticker}` (标准代码: `{clean_code}`)",
        f"- **标的类型**：{asset_type}",
        f"- **分析基准日**：`{trade_date}`",
        f"- **分析模式**：`Market Analyst Only` (技术量价分析 + 多空风控辩论)",
        f"- **最终投资评级**：**`{decision}`**",
        f"- **生成时间**：`{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`",
        "",
        "---",
        "",
        "## 🎯 核心投资决策 (Portfolio Decision)",
        "",
        f"{investment_plan}",
        "",
        "---",
        "",
        "## 📊 技术与量价研报 (Market Analyst Report)",
        "",
        f"{market_report}",
        "",
        "---",
        "",
        "## ⚔️ 投研多空辩论 (Bull vs Bear Debate)",
        "",
    ]

    if bull_history:
        report_lines.extend([
            "### 🐂 看多观点 (Bull Researcher)",
            f"{bull_history}",
            "",
        ])

    if bear_history:
        report_lines.extend([
            "### 🐻 看空观点 (Bear Researcher)",
            f"{bear_history}",
            "",
        ])

    if judge_decision:
        report_lines.extend([
            "### ⚖️ 综合研判方案 (Research Manager)",
            f"{judge_decision}",
            "",
        ])

    if trader_plan or risk_judge:
        report_lines.extend([
            "---",
            "",
            "## 🛡️ 交易计划与风控视图 (Trader & Risk Management)",
            "",
        ])
        if trader_plan:
            report_lines.extend([
                "### 📋 交易执行计划",
                f"{trader_plan}",
                "",
            ])
        if risk_judge:
            report_lines.extend([
                "### 🔍 风险辩论审查结论",
                f"{risk_judge}",
                "",
            ])

    report_lines.extend([
        "---",
        "",
        "*Report generated by [TradingAgents-Astock](https://github.com/Elgin996/TradingAgents-astock)*",
    ])

    return "\n".join(report_lines)


def run_quick_analysis(ticker: str, trade_date: str | None = None, output_file: str | None = None) -> str:
    """Execute quick analysis with Market Analyst only and save Markdown document."""
    clean_ticker = ticker.strip()
    clean_code = _normalize_ticker(clean_ticker)
    
    if not trade_date:
        trade_date = str(_market_today())
    
    is_etf = is_etf_ticker(clean_ticker)
    asset_desc = "ETF 基金" if is_etf else "股票"

    console.print(Panel.fit(
        f"[bold cyan]TradingAgents 快速投研分析[/bold cyan]\n"
        f"标的代码: [green]{clean_ticker}[/green] ({asset_desc}: {clean_code})\n"
        f"分析日期: [yellow]{trade_date}[/yellow]\n"
        f"分析模式: [magenta]仅 Market Analyst (技术量价分析)[/magenta]",
        border_style="cyan"
    ))

    # Initialize Graph with only market analyst
    config = DEFAULT_CONFIG.copy()
    config["selected_analysts"] = ["market"]
    
    ta = TradingAgentsGraph(
        selected_analysts=["market"],
        debug=False,
        config=config,
    )

    console.print("[dim]正在调取行情数据并执行多 Agent 辩论与决策...[/dim]")
    final_state, decision = ta.propagate(clean_ticker, trade_date)

    # Generate Markdown content
    md_content = format_markdown_report(clean_ticker, clean_code, trade_date, final_state, decision)

    # Save to file
    if output_file:
        out_path = Path(output_file).resolve()
    else:
        reports_dir = PROJECT_ROOT / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{clean_code}_{trade_date}.md"
        out_path = reports_dir / filename

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md_content, encoding="utf-8")

    console.print()
    console.print(Panel(
        f"[bold green]✅ 分析完成！[/bold green]\n\n"
        f"🎯 [bold]最终评级[/bold]: [cyan]{decision}[/cyan]\n"
        f"📄 [bold]Markdown 文档[/bold]: [link=file:///{out_path.as_posix()}]{out_path}[/link]",
        border_style="green",
        title="投研决策结果"
    ))

    return str(out_path)


def main():
    parser = argparse.ArgumentParser(
        description="TradingAgents 快速入口：默认仅运行 Market Analyst，输入代码直接输出 Markdown 报告"
    )
    parser.add_argument("ticker", nargs="?", help="股票或 ETF 代码 (例如 517520, 159242.etf, 600519)")
    parser.add_argument("date", nargs="?", default=None, help="分析基准日期 (YYYY-MM-DD，默认今天/最新交易日)")
    parser.add_argument("-o", "--output", default=None, help="自定义输出 Markdown 文件路径")

    args = parser.parse_args()

    ticker = args.ticker
    if not ticker:
        ticker = input("请输入股票或 ETF 代码 (如 517520.etf 或 600519): ").strip()
        if not ticker:
            console.print("[red]错误: 股票或 ETF 代码不能为空。[/red]")
            sys.exit(1)

    try:
        run_quick_analysis(ticker, args.date, args.output)
    except Exception as e:
        console.print(f"[bold red]❌ 执行失败: {e}[/bold red]")
        sys.exit(1)


if __name__ == "__main__":
    main()
